package GUI;

import CryptographyAlgorithm.AES;
import CryptographyAlgorithm.RSA;
import SteganographyAlgorithm.LSB;

import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Decode extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Decode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePathLabel = new javax.swing.JLabel();
        imagePathTextField = new javax.swing.JTextField();
        selectImageButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        steganoLabel = new javax.swing.JLabel();
        steganoComboBox = new javax.swing.JComboBox<>();
        cryptoComboBox = new javax.swing.JComboBox<>();
        cryptoLabel = new javax.swing.JLabel();
        secretKeyLabel = new javax.swing.JLabel();
        secretKeyPasswordField = new javax.swing.JPasswordField();
        decodeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        imagePathError = new javax.swing.JLabel();
        messageError = new javax.swing.JLabel();
        secretKeyError = new javax.swing.JLabel();
        steganoError = new javax.swing.JLabel();
        cryptoError = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();

        imagePathLabel.setText("Select Image");

        imagePathTextField.setEditable(false);

        selectImageButton.setText("Select");
        selectImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImageButtonActionPerformed(evt);
            }
        });

        messageLabel.setText("Result Message");

        steganoLabel.setText("Choose Decode method");

        steganoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LSB" }));

        cryptoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AES", "RSA" }));

        cryptoLabel.setText("Choose Decrypt method");

        secretKeyLabel.setText("Enter Secret Key / Private Key");

        decodeButton.setText("Decode");
        decodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decodeButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");

        imagePathError.setForeground(new java.awt.Color(255, 0, 0));

        messageError.setForeground(new java.awt.Color(255, 0, 0));

        secretKeyError.setForeground(new java.awt.Color(255, 0, 0));

        steganoError.setForeground(new java.awt.Color(255, 0, 0));

        cryptoError.setForeground(new java.awt.Color(255, 0, 0));

        messageTextArea.setEditable(false);
        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane2.setViewportView(messageTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagePathTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectImageButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 631, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decodeButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(steganoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(steganoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(steganoError)
                                .addGap(0, 229, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cryptoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cryptoError))
                            .addComponent(cryptoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(secretKeyPasswordField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagePathLabel)
                                .addGap(18, 18, 18)
                                .addComponent(imagePathError))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(messageLabel)
                                .addGap(18, 18, 18)
                                .addComponent(messageError))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(secretKeyLabel)
                                .addGap(18, 18, 18)
                                .addComponent(secretKeyError)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagePathLabel)
                    .addComponent(imagePathError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectImageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secretKeyLabel)
                    .addComponent(secretKeyError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secretKeyPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(steganoLabel)
                    .addComponent(cryptoLabel)
                    .addComponent(steganoError)
                    .addComponent(cryptoError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(steganoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cryptoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel)
                    .addComponent(messageError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decodeButton)
                    .addComponent(backButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectImageButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectImageButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);
        int i = fileChooser.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            imageFile = fileChooser.getSelectedFile();
            imageFilePath = imageFile.getPath();
            if (imageFilePath != null && !imageFilePath.isEmpty()) {
                imagePathTextField.setText(imageFilePath);
            }
        }
    }// GEN-LAST:event_selectImageButtonActionPerformed

    private void decodeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_decodeButtonActionPerformed

        // Get Values
        String imagePath = imagePathTextField.getText();
        String secretKey = new String(secretKeyPasswordField.getPassword());
        String steganoMethod = String.valueOf(steganoComboBox.getSelectedItem());
        String cryptoMethod = String.valueOf(cryptoComboBox.getSelectedItem());

        // Validation
        boolean validate = true;
        if (imagePath == null || imagePath.isEmpty()) {
            imagePathError.setText("Image File is required");
            validate = false;
        } else {
            imagePathError.setText("");
        }

        if (secretKey.isEmpty()) {
            secretKeyError.setText("Key is required");
            validate = false;
        } else {
            secretKeyError.setText("");
        }

        if (steganoMethod == null || steganoMethod.isEmpty()) {
            steganoError.setText("Select Decoding method");
            validate = false;
        } else {
            steganoError.setText("");
        }

        if (cryptoMethod == null || cryptoMethod.isEmpty()) {
            cryptoError.setText("Select Decrypting method");
            validate = false;
        } else {
            cryptoError.setText("");
        }

        if (!validate) {
            return;
        }

        // Pre-processing
        int slashIndex = imageFilePath.lastIndexOf("\\");
        int pointIndex = imageFilePath.lastIndexOf(".");
        String filePath = imageFilePath.substring(0, slashIndex);
        String fileName = imageFilePath.substring(slashIndex + 1, pointIndex);
        String fileExt = imageFilePath.substring(pointIndex + 1);

        // Image Decoding
        StringBuilder encryptedMessage = new StringBuilder();
        if (steganoMethod.equals("LSB")) {
            encryptedMessage = new StringBuilder(LSB.decode(filePath, fileName));
        }

        // Message Decryption
        String decryptedMessage = encryptedMessage.toString();
        try {
            decryptedMessage = switch (cryptoMethod) {
                case "AES" -> AES.decrypt(encryptedMessage.toString(), secretKey);
                case "RSA" ->
                    //originalMessage = RSAUtil.decrypt(message, secretKey);
                        RSA.decrypt(encryptedMessage.toString(), secretKey);
                default -> encryptedMessage.toString();
            };
        } catch (Exception e) {
            System.out.println("Something went wrong in Decryption");
            JOptionPane.showMessageDialog(this, "Something went wrong in Decryption", "Alert", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }

        // Display Message
        if (decryptedMessage != null && !decryptedMessage.isEmpty()) {
            System.out.println("Message has been decoded successfully");
            messageTextArea.setText(decryptedMessage);
            JOptionPane.showMessageDialog(this, "Message has been decoded successfully", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("Message couldn't be decoded");
            JOptionPane.showMessageDialog(this, "Message couldn't be decoded", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }// GEN-LAST:event_decodeButtonActionPerformed

    public void setActionListenerBackButton(java.awt.event.ActionListener actionListener) {
        backButton.addActionListener(actionListener);
    }

    private File imageFile;
    private String imageFilePath;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> cryptoComboBox;
    private javax.swing.JLabel cryptoError;
    private javax.swing.JLabel cryptoLabel;
    private javax.swing.JButton decodeButton;
    private javax.swing.JLabel imagePathError;
    private javax.swing.JLabel imagePathLabel;
    private javax.swing.JTextField imagePathTextField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel messageError;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JLabel secretKeyError;
    private javax.swing.JLabel secretKeyLabel;
    private javax.swing.JPasswordField secretKeyPasswordField;
    private javax.swing.JButton selectImageButton;
    private javax.swing.JComboBox<String> steganoComboBox;
    private javax.swing.JLabel steganoError;
    private javax.swing.JLabel steganoLabel;
    // End of variables declaration//GEN-END:variables
}
