package GUI;

import CryptographyAlgorithm.AES;
import CryptographyAlgorithm.RSA;

import javax.swing.JOptionPane;

public class Encrypt extends javax.swing.JPanel {

    /**
     * Creates new form Encrypt
     */
    public Encrypt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageLabel = new javax.swing.JLabel();
        messageError = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        cryptoLabel = new javax.swing.JLabel();
        cryptoError = new javax.swing.JLabel();
        cryptoComboBox = new javax.swing.JComboBox<>();
        secretKeyPasswordField = new javax.swing.JPasswordField();
        secretKeyLabel = new javax.swing.JLabel();
        secretKeyError = new javax.swing.JLabel();
        encryptedMessageLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        encryptedMessageTextArea = new javax.swing.JTextArea();
        encryptButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        messageLabel.setText("Enter Message");

        messageError.setForeground(new java.awt.Color(255, 0, 0));

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        cryptoLabel.setText("Choose Encrypt method");

        cryptoError.setForeground(new java.awt.Color(255, 0, 0));

        cryptoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AES", "RSA" }));

        secretKeyLabel.setText("Enter Secret Key / Public Key");

        secretKeyError.setForeground(new java.awt.Color(255, 0, 0));

        encryptedMessageLabel.setText("Encrypted Message");

        encryptedMessageTextArea.setEditable(false);
        encryptedMessageTextArea.setColumns(20);
        encryptedMessageTextArea.setRows(5);
        jScrollPane2.setViewportView(encryptedMessageTextArea);

        encryptButton.setText("Encrypt");
        encryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cryptoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(messageLabel)
                                .addGap(18, 18, 18)
                                .addComponent(messageError))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cryptoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(cryptoError)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(secretKeyLabel)
                                .addGap(18, 18, 18)
                                .addComponent(secretKeyError)
                                .addGap(0, 274, Short.MAX_VALUE))
                            .addComponent(secretKeyPasswordField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encryptedMessageLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(encryptButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel)
                    .addComponent(messageError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cryptoLabel)
                    .addComponent(cryptoError)
                    .addComponent(secretKeyLabel)
                    .addComponent(secretKeyError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cryptoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secretKeyPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(encryptedMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptButton)
                    .addComponent(backButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptButtonActionPerformed
        //Get Values
        String message = messageTextArea.getText();
        String secretKey = new String(secretKeyPasswordField.getPassword());
        String cryptoMethod = String.valueOf(cryptoComboBox.getSelectedItem());

        //Validation
        boolean validate = true;
        if (message == null || message.isEmpty()) {
            messageError.setText("Message is required");
            validate = false;
        } else {
            messageError.setText("");
        }

        if (secretKey.isEmpty()) {
            secretKeyError.setText("Key is required");
            validate = false;
        } else {
            secretKeyError.setText("");
        }

        if (cryptoMethod == null || cryptoMethod.isEmpty()) {
            cryptoError.setText("Select Encrypting method");
            validate = false;
        } else {
            cryptoError.setText("");
        }

        if (!validate) {
            return;
        }

        //Message Encryption
        String encryptedMessage = message;
        try {
            encryptedMessage = switch (cryptoMethod) {
                case "AES" -> AES.encrypt(message, secretKey);
                case "RSA" ->
                    //encryptedMessage = RSAUtil.encrypt(message, secretKey);
                        RSA.encrypt(message, secretKey);
                default -> message;
            };
        } catch (Exception e) {
            System.out.println("Something went wrong in Encryption");
            JOptionPane.showMessageDialog(this, "Something went wrong in Encryption", "Alert", JOptionPane.WARNING_MESSAGE);
            e.printStackTrace();
        }

        //Display Message
        if (encryptedMessage != null && !encryptedMessage.isEmpty()) {
            System.out.println("Message has been encrypted successfully");
            encryptedMessageTextArea.setText(encryptedMessage);
            JOptionPane.showMessageDialog(this, "Message has been encrypted successfully", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("Message couldn't be encrypted");
            JOptionPane.showMessageDialog(this, "Message couldn't be encrypted", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_encryptButtonActionPerformed

    public void setActionListenerBackButton(java.awt.event.ActionListener actionListener) {
        backButton.addActionListener(actionListener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> cryptoComboBox;
    private javax.swing.JLabel cryptoError;
    private javax.swing.JLabel cryptoLabel;
    private javax.swing.JButton encryptButton;
    private javax.swing.JLabel encryptedMessageLabel;
    private javax.swing.JTextArea encryptedMessageTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel messageError;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JLabel secretKeyError;
    private javax.swing.JLabel secretKeyLabel;
    private javax.swing.JPasswordField secretKeyPasswordField;
    // End of variables declaration//GEN-END:variables
}
