package GUI;

import java.awt.*;
import java.awt.event.ActionListener;

public class Home extends javax.swing.JPanel {

    MainWindow parentWindow;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greetingLabel = new javax.swing.JLabel();
        gotoEncodeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        gotoDecryptButton = new javax.swing.JButton();
        gotoEncryptButton = new javax.swing.JButton();
        gotoDecodeButton = new javax.swing.JButton();
        gotoKeyGeneratorButton = new javax.swing.JButton();

        greetingLabel.setFont(new java.awt.Font("Georgia", Font.BOLD, 24)); // NOI18N
        greetingLabel.setText("Welcome to LockNLoad");

        gotoEncodeButton.setText("Encode Image");
        gotoEncodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoEncodeButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        gotoDecryptButton.setText("Decrypt Text");

        gotoEncryptButton.setText("Encrypt Text");

        gotoDecodeButton.setText("Decode Image");
        gotoDecodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoDecodeButtonActionPerformed(evt);
            }
        });

        gotoKeyGeneratorButton.setText("Key Generator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gotoDecodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gotoEncryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gotoDecryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gotoEncodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gotoKeyGeneratorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addComponent(greetingLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(greetingLabel)
                .addGap(18, 18, 18)
                .addComponent(gotoEncodeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gotoDecodeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gotoEncryptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gotoDecryptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gotoKeyGeneratorButton)
                .addGap(33, 33, 33)
                .addComponent(exitButton)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gotoDecodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoDecodeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gotoDecodeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void gotoEncodeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 

    } 
    
    public void setActionListenerEncodeButton(ActionListener actionListener){
        gotoEncodeButton.addActionListener(actionListener);
    }
    
    public void setActionListenerDecodeButton(ActionListener actionListener){
        gotoDecodeButton.addActionListener(actionListener);
    }
    
    public void setActionListenerEncryptButton(ActionListener actionListener){
        gotoEncryptButton.addActionListener(actionListener);
    }
    
    public void setActionListenerDecryptButton(ActionListener actionListener){
        gotoDecryptButton.addActionListener(actionListener);
    }
    
    public void setActionListenerKeyGeneratorButton(ActionListener actionListener){
        gotoKeyGeneratorButton.addActionListener(actionListener);
    }
    
    public void setActionListenerExitButton(ActionListener actionListener){
        exitButton.addActionListener(actionListener);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton gotoDecodeButton;
    private javax.swing.JButton gotoDecryptButton;
    private javax.swing.JButton gotoEncodeButton;
    private javax.swing.JButton gotoEncryptButton;
    private javax.swing.JButton gotoKeyGeneratorButton;
    private javax.swing.JLabel greetingLabel;
    // End of variables declaration//GEN-END:variables
}
